"TODAY_STR=`date -u '+%Y-%m-%d-%H-%M-%S'`",
"npm install",
"ls -a",
"echo '===== Build Docker ======='",
"docker build -t 280341680746.dkr.ecr.us-west-2.amazonaws.com/iron-bank-frontend:latest .",
"echo '===== Push to ECR ======='",
"$(aws ecr get-login --region us-west-2 --no-include-email)",
"docker push 280341680746.dkr.ecr.us-west-2.amazonaws.com/iron-bank-frontend:latest",
"docker tag 280341680746.dkr.ecr.us-west-2.amazonaws.com/iron-bank-frontend:latest 280341680746.dkr.ecr.us-west-2.amazonaws.com/iron-bank-frontend:$TODAY_STR",
"docker push 280341680746.dkr.ecr.us-west-2.amazonaws.com/iron-bank-frontend:$TODAY_STR",
"echo '===== Push Latest Config to S3 for Elastic Beanstalk ======='",
"EB_APP_ZIP=eb_app_$TODAY_STR.zip",
"python3 generate_Dockerrun.aws.json.py --docker-image-tag 280341680746.dkr.ecr.us-west-2.amazonaws.com/iron-bank-frontend:$TODAY_STR",
"zip $EB_APP_ZIP Dockerrun.aws.json",
"aws s3 cp $EB_APP_ZIP s3://iron-bank-frontend-website/$EB_APP_ZIP"

"echo '===== Push the Elastic Beanstalk Prod Application Package to S3 ======='",
"EB_APP_ZIP=eb_app_prod.zip",
"python3 generate_Dockerrun.aws.json.py --docker-image-tag 280341680746.dkr.ecr.us-west-2.amazonaws.com/iron-bank-frontend:prod",
"zip $EB_APP_ZIP Dockerrun.aws.json",
"aws s3 cp $EB_APP_ZIP s3://iron-bank-frontend-website/$EB_APP_ZIP",
"echo '===== Push the prod tag Docker image to ECR ======='",
"$(aws ecr get-login --region us-west-2 --no-include-email)",
"docker pull 280341680746.dkr.ecr.us-west-2.amazonaws.com/iron-bank-frontend:latest",
"docker tag 280341680746.dkr.ecr.us-west-2.amazonaws.com/iron-bank-frontend:latest 280341680746.dkr.ecr.us-west-2.amazonaws.com/iron-bank-frontend:prod",
"docker push 280341680746.dkr.ecr.us-west-2.amazonaws.com/iron-bank-frontend:prod",
"echo '===== Create a new Prod Application Version for EB ======='",
"TODAY_STR=`date -u '+%Y-%m-%d-%H-%M-%S'`",
"aws elasticbeanstalk create-application-version --application-name iron-bank-front-end-docker --version-label prod-$TODAY_STR --source-bundle S3Bucket=iron-bank-frontend-website,S3Key=$EB_APP_ZIP",
"echo '===== Update the Environment with Newest Application  ======='",
"aws elasticbeanstalk update-environment --application-name iron-bank-front-end-docker --environment-name IronBankFrontEndDocker-env --version-label prod-$TODAY_STR "
